apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.castService.port }}  # Utilise la valeur de values.yaml
      targetPort: {{ .Values.service.castService.targetPort }}  # Port du conteneur
      nodePort: {{ .Values.service.castService.nodePort }}  # Port NodePort
  type: NodePort
