apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.movieService.port }}  # Utilise la valeur de values.yaml
      targetPort: {{ .Values.service.movieService.targetPort }}  # Port du conteneur
      nodePort: {{ .Values.service.movieService.nodePort }}  # Port NodePort
  type: NodePort
