# Paramètres d'images Docker
image:
  castService: "jenkins_devops_exams_cast_service:latest"
  movieService: "jenkins_devops_exams_movie_service:latest"

# Paramètres des services (les ports sont définis pour chaque environnement ci-dessous)
service:
  castService:
    port: 80              
    targetPort: 8000     
    nodePort: 30010    

  movieService:
    port: 80               
    targetPort: 8000     
    nodePort: 30011      

# Paramètres des bases de données
database:
  castDb:
    user: "ameliendb"
    password: "ameliendb"
    name: "cast_db"
    host: "cast-db"       
  movieDb:
    user: "ameliendb"
    password: "ameliendb"
    name: "movie_db"
    host: "movie-db"    
